#ifndef STPM_CONFIG_H
#define STPM_CONFIG_H

#define STPM_PORT PORTD
#define STPM_OUTPUT_PIN0 PIN4
#define STPM_OUTPUT_PIN1 PIN5
#define STPM_OUTPUT_PIN2 PIN6
#define STPM_OUTPUT_PIN3 PIN7

#define STPM_TIME 2   //2 MS IS THE HIGHEST SPEED

#endif
